package org.dergigi.fishyfishy

// Madeira coastal additions; see docs/GUIDE-SOURCES.md for occurrence and naming notes.
val coastalGuide = listOf(
    Species("saddled", "Saddled seabream", "Dobrada", "Brandbrasse", "Oblada melanura", R.drawable.saddled, "Fish",
        "Silver and oval, with a black saddle edged in white just before the forked tail. Often swims in groups.",
        "That dark saddle is a useful clue. Fish with similar silver bodies can have very different tail markings.",
        "Open water above shallow rocks", "Compare its tail patch with the white seabream.",
        listOf("Silver", "Schools"), "https://doris.ffessm.fr/ref/specie/720"),
    Species("two_banded", "Two-banded seabream", "Sargo-safia", "Zweibindenbrasse", "Diplodus vulgaris", R.drawable.two_banded, "Fish",
        "A silver body with two broad dark bands: one behind the head and another just before the tail.",
        "Its mouth can tackle little shellfish. Look for it searching near the bottom.",
        "Rocky shallows and nearby sand", "Find both dark bands without following the fish.",
        listOf("Silver", "Stripes", "Schools"), "https://www.fishbase.se/summary/Diplodus-vulgaris.html"),
    Species("mullet", "Golden grey mullet", "Tainha-dourada", "Goldmeeräsche", "Chelon auratus", R.drawable.mullet, "Fish",
        "A long silver body, small mouth and a gold mark on the gill cover. Other grey mullets look very similar.",
        "Mullets browse tiny food from surfaces and sediment. Watch for a little puff of sand as one feeds.",
        "Shallow bays, harbours and coastal rocks", "Can you see the golden cheek? If not, keep it uncertain.",
        listOf("Silver", "Schools"), "https://www.fishbase.se/summary/Chelon-auratus.html"),
    Species("goatfish", "Striped red mullet", "Salmonete", "Streifenbarbe", "Mullus surmuletus", R.drawable.goatfish, "Fish",
        "Two feelers under the chin, a sloping forehead and often a reddish line along the side. Colour changes with surroundings.",
        "Those chin feelers are called barbels. They help the fish find food hidden in sand.",
        "Sand and gravel beside rocks", "Watch the two barbels searching the sand.",
        listOf("Red", "Stripes", "Sand"), "https://www.fishbase.se/summary/Mullus-surmuletus.html"),
    Species("lizardfish", "Atlantic lizardfish", "Peixe-lagarto", "Atlantischer Eidechsenfisch", "Synodus saurus", R.drawable.lizardfish, "Fish",
        "An elongated mottled body resting on sand, with a broad pointed head and a large mouth. Similar lizardfish need careful comparison.",
        "Staying very still helps this hunter blend into the bottom while waiting for a smaller fish.",
        "Sand patches between rocks", "Can you find its outline against the sand?",
        listOf("Sand", "Camouflage", "Spots"), "https://www.fishbase.se/summary/Synodus-saurus.html"),
    Species("triplefin", "Black-faced triplefin", "Caboz-de-três-dorsais", "Gelber Spitzkopf-Schleimfisch", "Tripterygion delaisi", R.drawable.triplefin, "Fish",
        "A tiny fish perched on rocks, with three separate back fins. Breeding males are yellow with black faces; females and other males are brown and barred.",
        "A bright breeding male and a brown female can be the same species. Colour is only one clue!",
        "Small ledges and sheltered rocky surfaces", "Count the three back fins in the zoomed photo.",
        listOf("Small", "Yellow", "Dark", "Stripes"), "https://doris.ffessm.fr/ref/specie/823"),
    Species("redlip", "Eastern Atlantic redlip blenny", "Rói-anzóis", "Atlantischer Rotlippen-Schleimfisch", "Ophioblennius atlanticus", R.drawable.redlip, "Fish",
        "A blunt face with thick lips, a dark body and often blue edging on the fins. Perches close to rocks; colours vary.",
        "This little rock resident grazes algae. A favourite patch of rock can be its food cupboard.",
        "Very shallow rocky shores", "Watch whether it perches on rocks instead of schooling.",
        listOf("Small", "Dark", "Blue"), "https://www.fishbase.se/summary/Ophioblennius-atlanticus.html"),
    Species("toby", "Macaronesian sharpnose puffer", "Porquinho", "Makaronesischer Spitzkopfkugelfisch", "Canthigaster capistrata", R.drawable.toby, "Fish",
        "Small rounded body, pointed snout, pale belly and a brown back with blue lines or dots. Unlike the larger Guinean puffer, its nose looks sharply pointed.",
        "Small fins let this puffer manoeuvre carefully around rocks. Never make a puffer inflate: that is a stress response.",
        "Rocky reefs and algae-covered shallows", "Look for blue markings around its eyes and along its sides.",
        listOf("Small", "Blue", "Spots"), "https://www.fishbase.se/summary/Canthigaster-capistrata.html"),
    Species("puffer", "Guinean puffer", "Peixe-balão", "Guinea-Kugelfisch", "Sphoeroides marmoratus", R.drawable.puffer, "Fish",
        "A rounded fish with a blunt head, pale belly and mottled back. Dark spots run low along its sides; the tail can show dark bands.",
        "It can hover with little fin movements. Watch it quietly and never try to make it puff up.",
        "Rocky bottoms and nearby sandy patches", "Compare its round nose with the sharpnose puffer.",
        listOf("Spots", "Camouflage"), "https://ciesm.org/atlas/fishes_2nd_edition/Sphoeroides_marmoratus.pdf"),
    Species("scorpionfish", "Madeira rockfish", "Rascasso-da-Madeira", "Madeira-Drachenkopf", "Scorpaena maderensis", R.drawable.scorpionfish, "Fish",
        "A small mottled brown-red fish resting on rocks, with a broad spiny head. Other scorpionfish look similar.",
        "Camouflage helps it hide in plain sight. Its spines can sting, so give it space and keep hands off the rocks.",
        "Rocky shallows and algae-covered stones", "Find its eyes in the photo before looking for its body.",
        listOf("Camouflage", "Spines", "Red"), "https://www.fishbase.se/summary/Scorpaena-maderensis.html"),
    Species("black_moray", "Black moray", "Moreia-preta", "Schwarze Muräne", "Muraena augusti", R.drawable.black_moray, "Fish",
        "An eel-shaped dark fish with tiny pale spots, often showing only its head from a hole.",
        "A moray opens and closes its mouth to move water over its gills. Watch from outside its rocky home.",
        "Crevices and holes in rocky reefs", "Spot the small pale dots without approaching the hole.",
        listOf("Dark", "Spots", "Long"), "https://www.fishbase.se/summary/Muraena-augusti.html"),
    Species("moray", "Mediterranean moray", "Moreia-pintada", "Mittelmeer-Muräne", "Muraena helena", R.drawable.moray, "Fish",
        "A long eel-shaped body with irregular pale yellowish mottling on a dark background. Often hides in a rocky hole.",
        "Its flexible body can weave through rocky gaps. Never put hands into holes to look for one.",
        "Rocky shelters and crevices", "Compare its large mottled patches with the black moray’s tiny dots.",
        listOf("Spots", "Long", "Camouflage"), "https://www.fishbase.se/summary/Muraena-helena.html"),
    Species("trumpetfish", "Atlantic trumpetfish", "Peixe-trombeta", "Atlantischer Trompetenfisch", "Aulostomus strigosus", R.drawable.trumpetfish, "Fish",
        "A very long thin body with a tube-like snout and small fins far back. Can be brown, grey or yellow.",
        "Sometimes it hangs almost upright. That unusual posture can help it approach prey.",
        "Water above coastal rocky reefs", "Is it swimming horizontally or pointing its nose down?",
        listOf("Long", "Yellow"), "https://www.fishbase.se/summary/Aulostomus-strigosus.html"),
    Species("triggerfish", "Grey triggerfish", "Peixe-porco", "Grauer Drückerfisch", "Balistes capriscus", R.drawable.triggerfish, "Fish",
        "An oval, flattened grey body, small mouth and eyes high on the head. Look for a strong first spine on its back.",
        "The sturdy back spine can lock upright like a little trigger. Watch without disturbing its nest.",
        "Coastal rocks and sandy edges", "Watch the fins above and below its body ripple.",
        listOf("Grey", "Big"), "https://www.fishbase.se/summary/Balistes-capriscus.html"),
    Species("barracuda", "Yellowmouth barracuda", "Bicuda", "Gelbmaul-Barrakuda", "Sphyraena viridensis", R.drawable.barracuda, "Fish",
        "A long silver body with a pointed head, jutting lower jaw and dark bars along the upper sides. Similar barracudas need close comparison in a photo.",
        "A group can hover almost motionless before gliding away together. Enjoy watching from a distance.",
        "Open coastal water; encounters can be seasonal", "Notice the long body and widely separated back fins.",
        listOf("Silver", "Long", "Schools", "Stripes"), "https://www.fishbase.se/summary/Sphyraena-viridensis.html"),
    Species("sand_bream", "Sand steenbras", "Ferreira", "Marmorbrasse", "Lithognathus mormyrus", R.drawable.sand_bream, "Fish",
        "An elongated silver bream with many narrow vertical dark bars and a pointed snout.",
        "It searches the sandy bottom for small animals. Feeding fish can leave little clouds behind.",
        "Sandy shallows and bays", "Are the stripes vertical or running from head to tail?",
        listOf("Silver", "Sand", "Stripes", "Schools"), "https://www.fishbase.se/summary/Lithognathus-mormyrus.html"),
    Species("fireworm", "Bearded fireworm", "Verme-de-fogo", "Bart-Feuerborstenwurm", "Hermodice carunculata", R.drawable.fireworm, "Critters",
        "A segmented worm with fluffy white bristles along both sides and reddish tufts. Colour varies.",
        "Those fluffy-looking bristles are for protection and can sting. This is a creature to admire without touching.",
        "Rocks and the sea floor", "Count a few body segments with your eyes.",
        listOf("Red", "Long", "Bristles"), "https://doris.ffessm.fr/ref/specie/882"),
    Species("rock_crab", "Red rock crab", "Caranguejo-cabra", "Rote Felsenkrabbe", "Grapsus adscensionis", R.drawable.rock_crab, "Critters",
        "A broad, flat crab on wave-washed rocks. Adults can be bright red; younger ones are darker and mottled.",
        "Strong legs help it cling to slippery rocks as waves pass. It can scuttle sideways very quickly.",
        "Shoreline rocks around the waterline", "Watch from a safe dry spot: which way does it run?",
        listOf("Red", "Legs", "Shore"), "https://ifcn.madeira.gov.pt/images/Doc_Artigos/Garajau/PEOGRNPG.pdf"),
    Species("nimble_crab", "Nimble spray crab", "Caranguejo-aranha", "Flachkrabbe", "Percnon gibbesi", R.drawable.nimble_crab, "Critters",
        "A flat brownish crab with very long legs, often with yellowish bands at the joints. Usually tucked between shallow rocks.",
        "Its flat body lets it slip into narrow spaces. Tiny gaps can be big shelters for small animals.",
        "Shallow boulders and rocky cracks", "Look for long legs before looking for the hidden body.",
        listOf("Legs", "Camouflage", "Small"), "https://amaco.pt/wp-content/uploads/2024/10/05_Relatorio_IFCN_2023_final-optimized.pdf"),
    Species("arrow_crab", "Atlantic arrow crab", "Aranha-do-mar", "Atlantische Pfeilkrabbe", "Stenorhynchus lanceolatus", R.drawable.arrow_crab, "Critters",
        "A tiny triangular body with a long pointed nose and extremely thin, long legs. Looks a little like a walking arrow.",
        "Despite its spider-like legs, this is a crab. Its legs reach much farther than its little body.",
        "Shaded rocky ledges and crevices", "Find the pointed nose in the zoomed photo.",
        listOf("Legs", "Small"), "https://ifcn.madeira.gov.pt/pt/?catid=68%3Afauna&id=181%3Arnp-garajau-funchal&view=article"),
    Species("cleaner_shrimp", "Grabham’s cleaner shrimp", "Camarão-limpador", "Atlantische Weißband-Putzergarnele", "Lysmata grabhami", R.drawable.cleaner_shrimp, "Critters",
        "A small red-and-white shrimp with a white stripe down the back and long white antennae. Often sheltered beside a hole.",
        "It picks tiny parasites and scraps from fish. Even a big fish can visit a very small cleaner!",
        "Rocky shelters, sometimes near morays", "Watch the long antennae from outside the shelter.",
        listOf("Red", "Stripes", "Small", "Legs"), "https://doris.ffessm.fr/ref/specie/3926"),
    Species("black_urchin", "Black sea urchin", "Ouriço-do-mar-preto", "Schwarzer Seeigel", "Arbacia lixula", R.drawable.black_urchin, "Critters",
        "A black rounded urchin with dense, fairly short sturdy spines. Much shorter spines than the long-spined sea urchin.",
        "An urchin is an animal with a hard shell beneath its spines. Tiny tube feet help it hold onto rock.",
        "Shallow rocky surfaces", "Compare its spine length with the long-spined urchin.",
        listOf("Dark", "Spines"), "https://doris.ffessm.fr/ref/specie/1025"),
    Species("purple_urchin", "Purple sea urchin", "Ouriço-do-mar-comum", "Steinseeigel", "Paracentrotus lividus", R.drawable.purple_urchin, "Critters",
        "Short sturdy spines; can be purple, brown or green. Often carries bits of shell or algae, so colour alone is not enough.",
        "It can hold little bits of its surroundings over itself. Look for an urchin wearing a seaweed hat!",
        "Rocky shallows and pools", "Spot any shell fragments on top. Leave them there.",
        listOf("Spines", "Camouflage"), "https://www.marlin.ac.uk/species/detail/1499"),
    Species("sea_cucumber", "Brown sea cucumber", "Pepino-do-mar", "Braune Seegurke", "Holothuria sanctori", R.drawable.sea_cucumber, "Critters",
        "A thick brown sausage-shaped animal with small bumps, often surrounded by pale rings. Other sea cucumbers can look similar.",
        "It eats tiny food mixed into sediment. Sea cucumbers help recycle material on the sea floor.",
        "Sand, gravel and rocky shelters", "Can you spot the pale rings around its bumps?",
        listOf("Long", "Camouflage"), "https://doris.ffessm.fr/ref/specie/1744"),
    Species("club_anemone", "Club-tipped anemone", "Anémona-de-pontas-grossas", "Keulenanemone", "Telmatactis cricoides", R.drawable.club_anemone, "Critters",
        "A sea anemone with thick tentacles ending in rounded clubs. Can be cream, pink, orange or brown.",
        "It looks like a flower but is an animal. Its tentacles help catch food drifting nearby.",
        "Rocky crevices and ledges", "Look for the rounded tips without touching.",
        listOf("Tentacles", "Colourful"), "https://doris.ffessm.fr/ref/specie/1267"),
    Species("snakelocks", "Snakelocks anemone", "Anémona-verde", "Wachsrose", "Anemonia viridis", R.drawable.snakelocks, "Critters",
        "Many long waving tentacles, often green with purple tips, but some are brown. Compare the thin tips with the club-tipped anemone.",
        "Tiny algae living inside many of these anemones use sunlight to make food. The partners help each other.",
        "Sunlit shallow rocks and pools", "Watch the tentacles move with the water. Never touch them.",
        listOf("Tentacles", "Green"), "https://doris.ffessm.fr/ref/specie/111"),
    Species("sponge", "Yellow tube sponge", "Esponja-amarela", "Goldschwamm", "Aplysina aerophoba", R.drawable.sponge, "Critters",
        "Bright yellow fleshy tubes or lobes attached to rock, with an opening at the top. Shape varies; other yellow sponges exist.",
        "A sponge is an animal too! Water moves through its body, bringing tiny bits of food.",
        "Shallow rocky surfaces", "Find an opening at the top of a yellow tube.",
        listOf("Yellow"), "https://ifcn.madeira.gov.pt/en/areas-protegidas/garajau/valores-naturais.html"),
    Species("spiny_star", "Spiny sea star", "Estrela-do-mar-espinhosa", "Eisseestern", "Marthasterias glacialis", R.drawable.spiny_star, "Critters",
        "Usually five tapering arms with rows of obvious pale spines. More prickly-looking than the smooth-armed purple sea star.",
        "A sea star travels on tiny tube feet under its arms. Its slow journey takes patience to notice.",
        "Rocky bottoms and nearby sand", "Compare the arm texture with the purple sea star.",
        listOf("Arms", "Spines"), "https://www.marlin.ac.uk/species/detail/1688"),
    Species("limpet", "Rough limpet", "Lapa-branca", "Raue Napfschnecke", "Patella aspera", R.drawable.limpet, "Critters",
        "A low cone-shaped shell with rough radiating ribs, held tightly against rock. Several local limpets look alike; an overhead view may not identify the species.",
        "Under the shell is a sea snail. Its muscular foot grips the rock while it grazes tiny algae.",
        "Rocks at and just below the waterline", "Find the shell ridges with your eyes. Never prise it off the rock.",
        listOf("Shell", "Shore", "Small"), "https://oomdata.arditi.pt/products/MadeiraFish/index.php?id=241&page=viewfish"),
    Species("hermit_crab", "Tube-dwelling hermit crab", "Bernardo-eremita", "Röhren-Einsiedlerkrebs", "Calcinus tubularis", R.drawable.hermit_crab, "Critters",
        "A tiny hermit crab with spotted legs and a larger left claw. Can shelter in a shell or a fixed tube; other hermit crabs need careful comparison.",
        "A borrowed shell or empty tube protects its soft body. A home does not have to be built from scratch!",
        "Small shells and tubes on rocky bottoms", "Can you find its eyes peeking out of its home?",
        listOf("Shell", "Legs", "Small"), "https://doris.ffessm.fr/ref/specie/685"),
)
